version: "3.9"

services:
  app:
    build: .
    container_name: emoaid
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./pictures:/app/pictures
    environment:
      - PYTHONPATH=/app


    command: ["/app/venv/bin/python", "/app/entrypoints/main.py"]